package vista.paneles;

import index.MyFreeLab;
import src.Recursos;

public class PanelResumen extends javax.swing.JPanel {

    public PanelResumen() {
        initComponents();
        this.setSize(Recursos.tamDialogModal );
        this.setPreferredSize(Recursos.tamDialogModal );
        bkgAside.setImgBackgroundEnabled(true);
        bkgAside.setImgBackgroundIn_Ex(true);
        bkgAside.setImgRutaInterno(Recursos.bkgAside );
        mtdEstablecerIdioma();
    }
    
    private void mtdEstablecerIdioma(){
        
        // * Paneles
        tpanelInformativo.setTitleAt(0, MyFreeLab.idioma.getProperty("panelInforme.tpanelInformativo.tab1"));
        tpanelInformativo.setTitleAt(1, MyFreeLab.idioma.getProperty("panelInforme.tpanelInformativo.tab2"));
        
        // * Etiquetas
        this.lblProEnProceso.setText(MyFreeLab.idioma.getProperty("panelInforme.lblProEnProceso"));
        this.lblProFinalizados.setText(MyFreeLab.idioma.getProperty("panelInforme.lblProFinalizados"));
        this.lblProEliminados.setText(MyFreeLab.idioma.getProperty("panelInforme.lblProEliminados"));
        this.lblProTotales.setText(MyFreeLab.idioma.getProperty("panelInforme.lblProTotales"));
        
        this.lblMontoEsperado.setText(MyFreeLab.idioma.getProperty("panelInforme.lblMontoEsperado"));
        this.lblMontoPerdidas.setText(MyFreeLab.idioma.getProperty("panelInforme.lblMontoPerdidas"));
        this.lblMontoLibre.setText(MyFreeLab.idioma.getProperty("panelInforme.lblMontoLibre"));
        this.lblMontoObtenido.setText(MyFreeLab.idioma.getProperty("panelInforme.lblMontoObtenido"));
        
        this.etqTitulo.setText(MyFreeLab.idioma.getProperty("panelInforme.etqTitulo"));
        
        // * Campos (Placeholder)
        this.cmpProEnProceso.setPlaceholder(MyFreeLab.idioma.getProperty("panelInforme.lblProEnProceso"));
        this.cmpProFinalizados.setPlaceholder(MyFreeLab.idioma.getProperty("panelInforme.lblProFinalizados"));
        this.cmpProEliminados.setPlaceholder(MyFreeLab.idioma.getProperty("panelInforme.lblProEliminados"));
        this.cmpProTotales.setPlaceholder(MyFreeLab.idioma.getProperty("panelInforme.lblProTotales"));
        
        this.cmpMontoEsperado.setPlaceholder(MyFreeLab.idioma.getProperty("panelInforme.lblMontoEsperado"));
        this.cmpMontoPerdidas.setPlaceholder(MyFreeLab.idioma.getProperty("panelInforme.lblMontoPerdidas"));
        this.cmpMontoLibre.setPlaceholder(MyFreeLab.idioma.getProperty("panelInforme.lblMontoLibre"));
        this.cmpMontoObtenido.setPlaceholder(MyFreeLab.idioma.getProperty("panelInforme.lblMontoObtenido"));
        
        // * Mensajes
        this.lblMonMsg.setText(MyFreeLab.idioma.getProperty("panelInforme.lblMonMsg"));
        this.lblProMsg.setText(MyFreeLab.idioma.getProperty("panelInforme.lblProMsg"));
        
        // * Botones
        this.btnAceptar.setTexto(MyFreeLab.idioma.getProperty("panelInforme.btnAceptar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkgAside = new vista.componentes.jpanelbackground.JPanelBackground();
        jPanel1 = new javax.swing.JPanel();
        etqTitulo = new vista.componentes.etiqueta.Titulo();
        btnAceptar = new vista.componentes.boton.Boton();
        tpanelInformativo = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblProEliminados = new vista.componentes.etiqueta.Etiqueta();
        cmpProEliminados = new vista.componentes.campos.CampoDatos();
        lblProFinalizados = new vista.componentes.etiqueta.Etiqueta();
        lblProEnProceso = new vista.componentes.etiqueta.Etiqueta();
        cmpProEnProceso = new vista.componentes.campos.CampoTexto();
        cmpProFinalizados = new vista.componentes.campos.CampoTexto();
        lblProTotales = new vista.componentes.etiqueta.Etiqueta();
        cmpProTotales = new vista.componentes.campos.CampoTexto();
        lblProMsg = new vista.componentes.etiqueta.Mensaje();
        jPanel3 = new javax.swing.JPanel();
        lblMonMsg = new vista.componentes.etiqueta.Mensaje();
        lblMontoEsperado = new vista.componentes.etiqueta.Etiqueta();
        cmpMontoEsperado = new vista.componentes.campos.CampoTexto();
        lblMontoPerdidas = new vista.componentes.etiqueta.Etiqueta();
        cmpMontoPerdidas = new vista.componentes.campos.CampoTexto();
        lblMontoLibre = new vista.componentes.etiqueta.Etiqueta();
        cmpMontoLibre = new vista.componentes.campos.CampoTexto();
        lblMontoObtenido = new vista.componentes.etiqueta.Etiqueta();
        cmpMontoObtenido = new vista.componentes.campos.CampoTexto();

        bkgAside.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout bkgAsideLayout = new javax.swing.GroupLayout(bkgAside);
        bkgAside.setLayout(bkgAsideLayout);
        bkgAsideLayout.setHorizontalGroup(
            bkgAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        bkgAsideLayout.setVerticalGroup(
            bkgAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        etqTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etqTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqTitulo.setText("RESUMEN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etqTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etqTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        btnAceptar.setImgButtonType("success");
        btnAceptar.setTexto("Aceptar");

        lblProEliminados.setText("Proyectos eliminados");

        cmpProEliminados.setEditable(false);
        cmpProEliminados.setComponenteDidireccional(lblProEliminados);
        cmpProEliminados.setEnabled(false);
        cmpProEliminados.setFocusable(false);

        lblProFinalizados.setText("Proyectos finalizados");

        lblProEnProceso.setText("Proyectos en proceso");

        cmpProEnProceso.setEditable(false);
        cmpProEnProceso.setComponenteDidireccional(lblProEnProceso);
        cmpProEnProceso.setEnabled(false);
        cmpProEnProceso.setFocusable(false);

        cmpProFinalizados.setEditable(false);
        cmpProFinalizados.setComponenteDidireccional(lblProFinalizados);
        cmpProFinalizados.setEnabled(false);
        cmpProFinalizados.setFocusable(false);

        lblProTotales.setText("Proyectos en total");

        cmpProTotales.setEditable(false);
        cmpProTotales.setComponenteDidireccional(lblProTotales);
        cmpProTotales.setEnabled(false);
        cmpProTotales.setFocusable(false);

        lblProMsg.setText("Aquí se muestran un resumen de todo los proyectos en proceso, finalizados y eliminados.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmpProFinalizados, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(lblProFinalizados, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(cmpProEnProceso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpProEliminados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProEliminados, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(lblProEnProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmpProTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblProEnProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmpProEnProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblProTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmpProTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(cmpProFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cmpProEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        tpanelInformativo.addTab("Proyectos", jPanel2);

        lblMonMsg.setText("Aquí se muestran un resumen acerca de la monetización esperados de los proyectos.");

        lblMontoEsperado.setText("Monto esperado");

        cmpMontoEsperado.setEditable(false);
        cmpMontoEsperado.setComponenteDidireccional(lblMontoEsperado);
        cmpMontoEsperado.setEnabled(false);
        cmpMontoEsperado.setFocusable(false);

        lblMontoPerdidas.setText("Monto en perdidas");

        cmpMontoPerdidas.setEditable(false);
        cmpMontoPerdidas.setComponenteDidireccional(lblMontoPerdidas);
        cmpMontoPerdidas.setEnabled(false);
        cmpMontoPerdidas.setFocusable(false);

        lblMontoLibre.setText("Monto libre");

        cmpMontoLibre.setEditable(false);
        cmpMontoLibre.setComponenteDidireccional(lblMontoLibre);
        cmpMontoLibre.setEnabled(false);
        cmpMontoLibre.setFocusable(false);

        lblMontoObtenido.setText("Monto obtenido");

        cmpMontoObtenido.setEditable(false);
        cmpMontoObtenido.setComponenteDidireccional(lblMontoObtenido);
        cmpMontoObtenido.setEnabled(false);
        cmpMontoObtenido.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMontoEsperado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpMontoEsperado, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(lblMontoPerdidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpMontoPerdidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMontoLibre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpMontoLibre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMontoObtenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpMontoObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMonMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMontoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmpMontoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMontoObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmpMontoObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMontoPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmpMontoPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMontoLibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmpMontoLibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        tpanelInformativo.addTab("Monetización", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bkgAside, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tpanelInformativo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgAside, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tpanelInformativo, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.componentes.jpanelbackground.JPanelBackground bkgAside;
    public vista.componentes.boton.Boton btnAceptar;
    public vista.componentes.campos.CampoTexto cmpMontoEsperado;
    public vista.componentes.campos.CampoTexto cmpMontoLibre;
    public vista.componentes.campos.CampoTexto cmpMontoObtenido;
    public vista.componentes.campos.CampoTexto cmpMontoPerdidas;
    public vista.componentes.campos.CampoDatos cmpProEliminados;
    public vista.componentes.campos.CampoTexto cmpProEnProceso;
    public vista.componentes.campos.CampoTexto cmpProFinalizados;
    public vista.componentes.campos.CampoTexto cmpProTotales;
    public vista.componentes.etiqueta.Titulo etqTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private vista.componentes.etiqueta.Mensaje lblMonMsg;
    private vista.componentes.etiqueta.Etiqueta lblMontoEsperado;
    private vista.componentes.etiqueta.Etiqueta lblMontoLibre;
    private vista.componentes.etiqueta.Etiqueta lblMontoObtenido;
    private vista.componentes.etiqueta.Etiqueta lblMontoPerdidas;
    private vista.componentes.etiqueta.Etiqueta lblProEliminados;
    private vista.componentes.etiqueta.Etiqueta lblProEnProceso;
    private vista.componentes.etiqueta.Etiqueta lblProFinalizados;
    private vista.componentes.etiqueta.Mensaje lblProMsg;
    private vista.componentes.etiqueta.Etiqueta lblProTotales;
    private javax.swing.JTabbedPane tpanelInformativo;
    // End of variables declaration//GEN-END:variables
}
