/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles;

import index.MyFreeLab;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author victo
 */
public class PanelCardProyectos extends javax.swing.JPanel {

    /**
     * Creates new form PanelCard
     */
    public PanelCardProyectos() {
        initComponents();
        Dimension tam = new Dimension(676, 237);
        this.setPreferredSize( tam );
        this.setSize( tam );
        this.panelBackground.setBackground(new Color(40,175,176));
        this.panelBackground.setEnabled(true);
        this.panelBackground.setVisible(true);
        
        this.cmpCostoEstimado.getEstiloAprobado();
        this.cmpMontoInicial.getEstiloAprobado();
        this.cmpFechaFinal.getEstiloAprobado();
        this.cmpFechaInicial.getEstiloAprobado();
        
        mtdEstablecerIdioma();
    }
    
    public void mtdCardEliminadoProyecto(){
        panelAcciones.setBackground(new Color(141, 24, 22));
        btnModificar.setVisible(true);
        btnModificar.setEnabled(false);
        
        btnCotizar.setVisible(true);
        btnCotizar.setEnabled(false);

        mtdBorrarInformacion();
    }
    
    public void mtdCardActivoProyecto(){
        panelAcciones.setBackground(new Color(25,100,126));
        btnModificar.setVisible(true);
        
        btnCotizar.setVisible(true);
    }
    
    public void mtdCardRealizadoProyecto(){
        panelAcciones.setBackground(new Color(20, 89, 29));
        btnModificar.setVisible(false);
        
        btnCotizar.setVisible(true);
        btnCotizar.setEnabled(true);
        //btnCotizar.setTexto("Ver info.");
        this.btnCotizar.setTexto(MyFreeLab.idioma.getProperty("panelCardProyecto.btnVerInfo"));
    }
    
    private void mtdBorrarInformacion(){
        panelInformacion.setVisible(false);
        Dimension tamTarjeta = new Dimension(676, 125);
        //Dimension tamTarjeta = new Dimension(676, 152);
        this.setPreferredSize(tamTarjeta );
        this.setSize(tamTarjeta );
    }
    
    private void mtdEstablecerIdioma(){
        
        // * Etiquetas
        this.lblFechaInicial.setText(MyFreeLab.idioma.getProperty("panelCardProyecto.lblFechaInicial"));
        this.lblFechaFinal.setText(MyFreeLab.idioma.getProperty("panelCardProyecto.lblFechaFinal"));
        this.lblMontoInicial.setText(MyFreeLab.idioma.getProperty("panelCardProyecto.lblMontoInicial"));
        this.lblMontoEstimado.setText(MyFreeLab.idioma.getProperty("panelCardProyecto.lblMontoEstimado"));
        
        // * Botones
        this.btnCotizar.setTexto(MyFreeLab.idioma.getProperty("panelCardProyecto.btnCotizar"));
        this.btnModificar.setTexto(MyFreeLab.idioma.getProperty("panelCardProyecto.btnModificar"));
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBackground = new vista.componentes.jpanelbackground.JPanelBackground();
        panelAcciones = new javax.swing.JPanel();
        btnCotizar = new vista.componentes.boton.Boton();
        btnModificar = new vista.componentes.boton.Boton();
        etqTitulo = new vista.componentes.etiqueta.Titulo();
        pgrProyecto = new javax.swing.JProgressBar();
        panelInformacion = new javax.swing.JPanel();
        lblFechaInicial = new vista.componentes.etiqueta.Etiqueta();
        cmpFechaInicial = new vista.componentes.campos.CampoTexto();
        cmpFechaFinal = new vista.componentes.campos.CampoTexto();
        cmpMontoInicial = new vista.componentes.campos.CampoTexto();
        cmpCostoEstimado = new vista.componentes.campos.CampoTexto();
        lblFechaFinal = new vista.componentes.etiqueta.Etiqueta();
        lblMontoInicial = new vista.componentes.etiqueta.Etiqueta();
        lblMontoEstimado = new vista.componentes.etiqueta.Etiqueta();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 204));

        panelBackground.setBackground(new java.awt.Color(40, 175, 176));
        panelBackground.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        panelBackground.setImgOpacidad(1.0F);
        panelBackground.setImgRutaInternoActivo(false);

        panelAcciones.setBackground(new java.awt.Color(25, 100, 126));

        btnCotizar.setTexto("Cotizar");

        btnModificar.setAutoscrolls(true);
        btnModificar.setImgButtonType("info");
        btnModificar.setTexto("Agregar requisito");

        javax.swing.GroupLayout panelAccionesLayout = new javax.swing.GroupLayout(panelAcciones);
        panelAcciones.setLayout(panelAccionesLayout);
        panelAccionesLayout.setHorizontalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAccionesLayout.setVerticalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCotizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        etqTitulo.setBackground(new java.awt.Color(0, 0, 0));
        etqTitulo.setText("Titulo del proyecto");

        panelInformacion.setBackground(new java.awt.Color(255, 255, 255));

        lblFechaInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaInicial.setText("Fecha inicial");

        cmpFechaInicial.setEditable(false);
        cmpFechaInicial.setBorder(null);
        cmpFechaInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmpFechaInicial.setText("campoTexto1");

        cmpFechaFinal.setEditable(false);
        cmpFechaFinal.setBorder(null);
        cmpFechaFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmpFechaFinal.setText("campoTexto2");

        cmpMontoInicial.setEditable(false);
        cmpMontoInicial.setBorder(null);
        cmpMontoInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmpMontoInicial.setText("campoTexto3");

        cmpCostoEstimado.setEditable(false);
        cmpCostoEstimado.setBorder(null);
        cmpCostoEstimado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmpCostoEstimado.setText("campoTexto4");

        lblFechaFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaFinal.setText("Fecha final");

        lblMontoInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMontoInicial.setText("Monto inicial");

        lblMontoEstimado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMontoEstimado.setText("Monto estimado");

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmpFechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmpFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(lblFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMontoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmpMontoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMontoEstimado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmpCostoEstimado, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmpFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpMontoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpCostoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etqTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addComponent(pgrProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etqTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pgrProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public vista.componentes.boton.Boton btnCotizar;
    public vista.componentes.boton.Boton btnModificar;
    public vista.componentes.campos.CampoTexto cmpCostoEstimado;
    public vista.componentes.campos.CampoTexto cmpFechaFinal;
    public vista.componentes.campos.CampoTexto cmpFechaInicial;
    public vista.componentes.campos.CampoTexto cmpMontoInicial;
    public vista.componentes.etiqueta.Titulo etqTitulo;
    private javax.swing.JPanel jPanel1;
    public vista.componentes.etiqueta.Etiqueta lblFechaFinal;
    private vista.componentes.etiqueta.Etiqueta lblFechaInicial;
    private vista.componentes.etiqueta.Etiqueta lblMontoEstimado;
    public vista.componentes.etiqueta.Etiqueta lblMontoInicial;
    private javax.swing.JPanel panelAcciones;
    private vista.componentes.jpanelbackground.JPanelBackground panelBackground;
    public javax.swing.JPanel panelInformacion;
    public javax.swing.JProgressBar pgrProyecto;
    // End of variables declaration//GEN-END:variables
}
