/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles;

import java.awt.Dimension;
import src.Info;

/**
 *
 * @author victo
 */
public class PanelAcercaDe extends javax.swing.JPanel {
    
    
    
    /**
     * Creates new form panel_acerca_de
     */
    public PanelAcercaDe() {
        initComponents();
    
        // Establecer propiedades para el panel
        Dimension tamahno = new Dimension(660, 498);
        setSize(tamahno);
        setPreferredSize(tamahno);
        btnAceptar.setEnabled(false);
        
        // Establecer información para la licencia
        String licencia = txt_licencia.getText();
        lbl_Software.setText( Info.NombreSoftware );
        lbl_Licencia.setText( Info.Licencia );
        licencia = licencia.replace("<name of author>", Info.Autor );
        licencia = licencia.replace("<name of program>", Info.sNombre );
        licencia = licencia.replace("<version of program>", Info.sVersion );
        licencia = licencia.replace("<year>", Info.Anho );
        licencia = licencia.replace("<description>", Info.Descripcion );
        licencia = licencia.replace("<details>", Info.Detalle);
        txt_licencia.setText(licencia);
        txt_licencia.setCaretPosition(0);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Licencia = new vista.componentes.etiqueta.Enlace();
        btnAceptar = new vista.componentes.boton.Boton();
        contendor_licencia = new javax.swing.JScrollPane();
        txt_licencia = new javax.swing.JTextArea();
        lbl_Software = new vista.componentes.etiqueta.Titulo();

        lbl_Licencia.setText("Licencia");

        btnAceptar.setImgButtonType("dark");
        btnAceptar.setTexto("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAceptarMouseReleased(evt);
            }
        });

        txt_licencia.setEditable(false);
        txt_licencia.setColumns(20);
        txt_licencia.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txt_licencia.setLineWrap(true);
        txt_licencia.setRows(5);
        txt_licencia.setText("Copyright (C) <year>  <name of author>\n\n<name of program> <version of program>\n\n<description>\n<details>\n\nThis program is free software: you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation, either version 3 of the License, or\n(at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program.  If not, see <https://www.gnu.org/licenses/>.");
        txt_licencia.setWrapStyleWord(true);
        txt_licencia.setCaretPosition(0);
        txt_licencia.setMargin(new java.awt.Insets(10, 10, 10, 10));
        contendor_licencia.setViewportView(txt_licencia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contendor_licencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lbl_Software, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(lbl_Licencia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Software, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lbl_Licencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contendor_licencia, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public vista.componentes.boton.Boton btnAceptar;
    public javax.swing.JScrollPane contendor_licencia;
    private vista.componentes.etiqueta.Enlace lbl_Licencia;
    private vista.componentes.etiqueta.Titulo lbl_Software;
    public javax.swing.JTextArea txt_licencia;
    // End of variables declaration//GEN-END:variables
}
