/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ventanas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import src.Source;
import vista.componentes.jpanelbackground.Background;
import vista.paneles.panel_acerca_de;

/**
 *
 * @author victo
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    public VentanaInicio(  ) {
    }   

    public VentanaInicio(JPanel panel) {
        initComponents();
        
        // Posicionarlo al centro
        this.setLocationRelativeTo(null);
        
        //
        panel.setBounds(0, 0, this.panelContenedor.getWidth(), this.panelContenedor.getHeight());
        this.panelContenedor.add(panel );
        this.panelContenedor.validate();
        this.panelContenedor.repaint();
        this.panelContenedor = panel;
        
        // Establecer el fondo de la ventana
        this.panel_background.setImgRutaInterno( Source.bkgDefault );
        
        // ** Testing **
        System.out.println("Tamaño de la ventana = " + this.getBounds());
        System.out.println("Tamaño del panel = " + this.panel_background.getBounds());

    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_background = new vista.componentes.jpanelbackground.JPanelBackground();
        panelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_Salir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItem_AcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_background.setImgBackgroundEnabled(true);
        panel_background.setImgRutaExterno(new java.io.File("C:\\Program Files\\NetBeans 8.2\\<Not Set>"));

        panelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelContenedor.setOpaque(false);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1105, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_backgroundLayout = new javax.swing.GroupLayout(panel_background);
        panel_background.setLayout(panel_backgroundLayout);
        panel_backgroundLayout.setHorizontalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backgroundLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panel_backgroundLayout.setVerticalGroup(
            panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backgroundLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(227, 36));

        jMenu1.setText("Archivo");

        menuItem_Salir.setText("Salir");
        menuItem_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuItem_SalirMouseReleased(evt);
            }
        });
        jMenu1.add(menuItem_Salir);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Editar");

        jMenuItem4.setText("Mis datos");
        jMenu3.add(jMenuItem4);

        jMenuItem9.setText("Buscar proyecto");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Gestionar empresas");
        jMenu3.add(jMenuItem10);

        jMenuItem12.setText("Gestionar proyectos");
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Configurar");

        jMenuItem8.setText("Conexion");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ayuda");

        menuItem_AcercaDe.setText("Acerca de");
        menuItem_AcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuItem_AcercaDeMouseReleased(evt);
            }
        });
        jMenu5.add(menuItem_AcercaDe);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_AcercaDeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem_AcercaDeMouseReleased
        this.fncAcercaDe();
    }//GEN-LAST:event_menuItem_AcercaDeMouseReleased

    private void menuItem_SalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem_SalirMouseReleased
        // TODO add your handling code here:
        this.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItem_SalirMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem10;
    public javax.swing.JMenuItem jMenuItem12;
    public javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    public javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuItem_AcercaDe;
    public javax.swing.JMenuItem menuItem_Salir;
    private javax.swing.JPanel panelContenedor;
    private vista.componentes.jpanelbackground.JPanelBackground panel_background;
    // End of variables declaration//GEN-END:variables
    private JDialog modal = new JDialog(this, true);
    private panel_acerca_de panelAcercaDe = null;
    
    public JPanel getPanelContenedor() {
        return panelContenedor;
    }
    
    // Este metodo crea un modal para AcercaDe
    private void fncAcercaDe() {
        
        // Patron de diseño Singleton 
        if( panelAcercaDe == null ){
            panelAcercaDe = new panel_acerca_de();
        }
        
        // Establecemos las propiedades para AcercaDe
        panelAcercaDe.init();
        modal.setDefaultCloseOperation( JFrame.DO_NOTHING_ON_CLOSE );
        modal.setResizable(false);
        modal.setTitle("Acerca de");
        modal.setLocation( 662, 293 );
        modal.setPreferredSize(panelAcercaDe.getSize());
        modal.setSize(panelAcercaDe.getSize());
        panelAcercaDe.setBounds(0, 0, panelAcercaDe.getWidth(), panelAcercaDe.getHeight());
        panelAcercaDe.btnAceptar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if( panelAcercaDe.btnAceptar.isEnabled() ){
                    panelAcercaDe.contendor_licencia.setBorder(null);
                    modal.setVisible(false);
                    modal.dispose();
                }
                //System.out.println("location ventana = " + getLocation() );
                //System.out.println("location modal = " + modal.getLocation() );
            }
        });
        
        // Se agrega el panel de acerca de y se muestra el modal
        modal.add( panelAcercaDe );
        modal.setVisible(true);
    }
    
    
}
